export const Color = {
  blue: '#A1C8E9',
  green: '#BCDFC9',
  pink: '#F6C2D9',
  yellow: '#FFF69B',
  purple: '#C9AFFF',
  accentBlue: '#B3DCFF',
  accentGreen: '#D9FFE7',
  accentPink: '#FFE1EE',
  accentYellow: '#FFF9BA',
  accentPurple: '#DBCAFF',
  backgroundPrimary: '#E4DAE2',
  backgroundSecondary: '#ECECEC',
  grey: '#666666',
  textSecondary: '#000000',
} as const;